server:
  address: localhost
  port: 8080
#JPA
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ScanSavvy
      authentication-database: admin
      username: root
      password: 4788


  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR