server:
  address: localhost
  port: 8080
#JPA
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: scansavvy
      authentication-database: admin
      username: root
      password: 4788

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR